export const AppActionTypes = {
    SET_API_SERVER_PORT: "SET_API_SERVER_PORT",
    SET_PROGRAM_AVAILABLE: "SET_PROGRAM_AVAILABLE",
    SET_CURRENT_PROGRAM_NAME: "SET_CURRENT_PROGRAM_NAME",
    SET_CURRENT_EXERCISE: "SET_CURRENT_EXERCISE"
}